[PPWP-37] - [GET] Validação dos Campos
PluginAndPartners/cart-prestashop-7 pull request #136
Opened 2021-07-13 18:07 UTC by cleitonaguiarandrade

Validar o recebimento de todos os campos enviados pelo CoreNotifier, caso não seja válido, utilizar o status code correto para responder (400 Bad Request)

2021-07-13 18:11 UTC, SalehKhalilMP requested changes

2021-07-13 18:11 UTC, SalehKhalilMP commented on controllers/front/notifier.php
> +                    'Deu tudo certo',
Acho interessante seguir um padrão de responder em inglês, assim como na resposta de erro por exemplo.

2021-07-13 18:54 UTC, SalehKhalilMP approved these changes

2021-07-14 14:04 UTC, maicongouveia approved these changes

2021-07-14 14:12 UTC, GiovanniCavallari requested changes

2021-07-14 14:12 UTC, GiovanniCavallari commented on controllers/front/notifier.php
> +            $time_stamp = Tools::getValue('timestamp');
Seria bom escrever timestamp tudo junto para manter o padrão entre plugins e o core.

2021-07-14 14:34 UTC, GiovanniCavallari approved these changes

2021-07-14 14:34 UTC, merged