[PPWP-38] - [GET] Verificação do Token
PluginAndPartners/cart-prestashop-7 pull request #137
Opened 2021-07-14 14:40 UTC by cleitonaguiarandrade

Colocar validação do token hmac utilizando os helpers

2021-07-14 20:01 UTC, maicongouveia approved these changes

2021-07-15 19:03 UTC, SalehKhalilMP requested changes

2021-07-15 19:03 UTC, SalehKhalilMP commented on controllers/front/notifier.php
> +                }
Acredito que o código poderia ficar mais limpo, usando um conceito chamado early return, ou seja, utilizarmos return como saída para a nossa função ao invés de utilizarmos um else ou elseif, reduzindo a complexidade ciclomatica. Exemplo:

```php
               if (!$token) {
                    return $this->getNotificationResponse('Unauthorized', 401);
                }

               if ($auth === $token) {
                    return $this->getNotificationResponse('Authorized', 200);
                }
                
              return $this->getNotificationResponse('Some parameters are empty', 400);     

```

O que acha?

2021-07-16 17:04 UTC, cleitonaguiarandrade commented on controllers/front/notifier.php
> +                }
Feito!

2021-07-16 18:09 UTC, SalehKhalilMP approved these changes

2021-07-16 18:11 UTC, maicongouveia commented on controllers/front/notifier.php
> +            null
Acho que isso aqui esta errado, não tem um terceiro parametro

2021-07-16 18:38 UTC, cleitonaguiarandrade commented on controllers/front/notifier.php
> +            null
Pronto @maicongouveia

2021-07-16 18:43 UTC, merged