Feature/psw 439/listado de meios de pago
PluginAndPartners/cart-prestashop-7 pull request #256
Opened 2022-11-01 22:30 UTC by cleitonaguiarandrade

## 📝 Description

## 🎯 Goals

>We have set the plugin to get all payment methods from bifrost API instead of Mercado Pago API.

> - [ ] PLATFORM_ID still needs to be defined
> -[x]We have removed the function used as a mock to get the payment places related to paycash, and also refactored the function responsible for checking when payment type is paycash and adding the key payment_places ro the array.
> -[x]The endpoint used now is '/v1/bifrost/payment-methods' opposed to the endpoint used before that was '/v1/payment-methods'

## 🧰 How to reproduce

> - You just need to install he MercadoPago plugin for PrestaShop, configure it and activate the checkouts of your preference to be shown on the checkout page

2022-11-03 12:19 UTC, AlberAlmeida approved these changes

2022-11-03 13:32 UTC, dmsantosd approved these changes

2022-11-03 18:02 UTC, luiztucillo requested changes

2022-11-03 18:02 UTC, luiztucillo commented on includes/MPApi.php
>              if ($value['id'] == 'paycash') {
Precisamos retirar o `if` do `paycash`
Hoje é o único que tem `payment_places`, mas se surgir algum novo que tenha, por padrão, já tem que funcionar vindo da API.
Ou seja, se tiver `payment_places`, independente do `payment_method`, ele deve ser exibido.

2022-11-08 21:57 UTC, luiztucillo approved these changes

2022-11-16 18:43 UTC, merged