Fixed decimal value when creating Pro checkout preference
PluginAndPartners/cart-prestashop-7 pull request #262
Opened 2022-11-23 19:28 UTC by katelucena-meli

Correção do valor decimal na criação da preferência do checkout Pro, para 2 casas decimais.
https://mercadolibre.atlassian.net/browse/PPSOPORTE1-671

2022-11-24 16:55 UTC, raytotti approved these changes

2022-11-28 15:22 UTC, cleitonaguiarandrade approved these changes

2022-11-29 13:24 UTC, luiztucillo requested changes

2022-11-29 13:24 UTC, luiztucillo commented on includes/module/preference/AbstractPreference.php
> +                'unit_price' => $this->getCalculateDecimalUnitPrice($round, $discounts),
Kate, aqui não deveria ser negativo como estava no antigo?

2022-11-29 13:24 UTC, luiztucillo commented on includes/module/preference/AbstractPreference.php
> +        $cartTotal = $this->getCalculateDecimalCartTotal($round, $cart);
Aqui não poderia usar a mesma função do anterior e já passar o `$cart->getOrderTotal()`?

2022-11-29 13:58 UTC, katelucena-meli commented on includes/module/preference/AbstractPreference.php
> +        $cartTotal = $this->getCalculateDecimalCartTotal($round, $cart);
Deveria sim, ajustado!

2022-11-29 13:58 UTC, katelucena-meli commented on includes/module/preference/AbstractPreference.php
> +                'unit_price' => $this->getCalculateDecimalUnitPrice($round, $discounts),
Deveria sim, ajustado!

2022-11-29 14:00 UTC, luiztucillo approved these changes

2022-11-29 14:02 UTC, katelucena-meli commented on includes/module/preference/AbstractPreference.php
> +        $cartTotal = $this->getCalculateDecimalCartTotal($round, $cart);
`$cart->getOrderTotal()` , ele já está sendo chamado assim dentro da função` getCalculateDecimalCartTotal()`

2022-11-29 14:02 UTC, merged